arm:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    constraints:
      stopped_velocity_tolerance: 0.0
    # gains:
    #   joint0:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   joint1:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   joint2:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   joint3:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   joint4:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   joint5:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}



  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - finger_joint1
      - finger_joint2
    constraints:
      stopped_velocity_tolerance: 0.0
    # gains:
    #   finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
    #   finger_joint2:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

  # gazebo_ros_control:
  #   pid_gains:
  #     joint0:   {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 0.0}
  #     joint1:   {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 0.0}
  #     joint2:   {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 0.0}
  #     joint3:   {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 0.0}
  #     joint4:   {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 0.0}
  #     joint5:   {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 0.0}
  #     finger_joint1:  {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 1.0}
  #     finger_joint2:  {p: 10000.0, i: 10.0, d: 0.01, i_clamp: 1.0}