controller_frequency: 10.0
controller_patience: 15.0

planner_frequency: 2.0
planner_patience: 5.0

conservative_reset_dist: 3.0

oscillation_timeout: 5.0
oscillation_distance: 0.5

clearing_rotation_allowed: false
# DWA Planner specific parameters (you can use other planners as well)
# DWAPlannerROS:
#   max_vel_x: 1.0  # Maximum forward velocity
#   min_vel_x: -1.0  # Minimum forward velocity (to move forward)
#   max_vel_theta: 0.5  # Maximum rotational velocity
#   min_vel_theta: -0.5  # Minimum rotational velocity (to move backward)
#   acc_lim_x: 1.0  # Maximum acceleration in x-direction
#   acc_lim_theta: 1.0  # Maximum rotational acceleration
#   xy_goal_tolerance: 0.1  # Tolerance in distance to the goal
#   yaw_goal_tolerance: 0.1  # Tolerance in angle to the goal
#   latch_xy_goal_tolerance: false  # Latch goal tolerance
#   forward_point_distance: 0.325  # Distance to look ahead in meters
#   stop_time_buffer: 0.2  # How long to allow for stopping in seconds
#   scaling_speed: 0.25  # The speed at which to start scaling the robot's speed
#   max_scaling_factor: 0.2  # The maximum scaling factor
#   path_distance_bias: 32.0
#   goal_distance_bias: 20.0
#   occdist_scale: 1.6  # 增加障碍物距离的权重
#   forward_point_distance: 0.5  # 增大前向预测距离
