controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint1
      - finger_joint2
initial:  # Define initial robot poses per group
  - group: arm
    pose: home